name: wahaj_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: any
  intl_translation: any
  meta: ^1.15.0
  modal_progress_hud_nsn: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # ğŸ”¹ ØªØ¹Ø±ÙŠÙ Ø§Ù„Ø®Ø·ÙˆØ·
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Regular.ttf
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alexandria-Light.ttf
          weight: 300
        - asset: assets/fonts/Alexandria-Thin.ttf
          weight: 100
        - asset: assets/fonts/Alexandria-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Alexandria-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Alexandria-Black.ttf
          weight: 900

  # ğŸ”¹ ØªØ¹Ø±ÙŠÙ Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª SVG
  assets:
    - assets/icons/
